apps/cart/urls.py
from django.urls import include
from django.urls import re_path
from django.urls import path
from .views import CartAddView
from .views import CartInfoView
from .views import CartUpdateView
from .views import CartDeleteView

# app_name = 'cart'
urlpatterns = [
    path('add', CartAddView.as_view(), name='add'),  # 购物车记录添加
    path('', CartInfoView.as_view(), name='show'),  # 购物车页面显示
    path('update', CartUpdateView.as_view(), name='update'),  # 购物车记录更新
    path('delete', CartDeleteView.as_view(), name='delete'),  # 购物车记录删除

]

apps/goods/urls.py
from django.urls import include
from django.urls import re_path
from django.urls import path
from .views import IndexView
from .views import DetailView
from .views import ListView

# app_name = 'goods'

urlpatterns = [
    path('index', IndexView.as_view(), name='index'),  # 首页
    re_path(r'^goods/(?P<goods_id>\d+)$', DetailView.as_view(), name='detail'),  # 详情页
    re_path(r'^list/(?P<type_id>\d+)/(?P<page>\d+)$', ListView.as_view(), name='list')  # 列表页
]

apps/user/urls.py
from django.urls import include
from django.contrib.auth.decorators import login_required
from django.urls import re_path
from django.urls import path
from .views import RegisterView
from .views import ActiveView
from .views import LoginView
from .views import UserInfoView
from .views import UserOrderView
from .views import AddressView
from .views import LogoutView

# from . import views

urlpatterns = [
    # path('register', views.register, name='register'),  # 注册
    # path('register_handle', views.register_handle, name='register_handle'),  # 注册处理

    path('register', RegisterView.as_view(), name='register'),  # 注册
    re_path(r'^active/(?P<token>.*)$', ActiveView.as_view(), name='active'),  # 用户激活
    path('login', LoginView.as_view(), name='login'),  # 登录
    path('logout', LogoutView.as_view(), name='logout'),  # 退出登录

    # path('', login_required(UserInfoView.as_view()), name='user'),  # 用户中心-信息页
    # path('order', login_required(UserOrderView.as_view()), name='order'),  # 用户中心-订单页
    # path('address', login_required(AddressView.as_view()), name='address')  # 用户中心-地址页

    path('', UserInfoView.as_view(), name='user'),  # 用户中心-信息页
    path('order', UserOrderView.as_view(), name='order'),  # 用户中心-订单页
    path('address', AddressView.as_view(), name='address')  # 用户中心-地址页
]

dailyfresh/urls.py
from django.contrib import admin
from django.urls import include
from django.urls import re_path
from django.urls import path

# 注意！ include()第一个参数是一个元组！！！是('应用名称.urls','应用名称')
# 即为：include(('应用名称.urls','应用名称')，namespace='XXXXXXX')
# https://www.cnblogs.com/wendaobiancheng/p/9109257.html

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path(r'^tinymce/', include(('tinymce.urls', 'tinymce'), namespace='tinymce')),  # 富文本编辑器
    re_path(r'^search/', include(('haystack.urls', 'haystack'), namespace='haystack')),  # 全文检索框架
    re_path(r'^user/', include(('user.urls', 'user'), namespace='user')),  # 用户模块
    re_path(r'cart/', include(('cart.urls', 'cart'), namespace='cart')),  # 购物车模块
    re_path(r'order/', include(('order.urls', 'order'), namespace='order')),  # 订单模块
    path('', include(('goods.urls', 'goods'), namespace='goods')),  # 商品模块(要放在最后！防止被抢先匹配)

    # re_path(r'^tinymce/', include('tinymce.urls',namespace='tinymce')),  # 富文本编辑器

]

apps/cart/models.py
from db.base_model import BaseModel
from django.db import models


# Create your models here.
# 使用redis实现购物车的功能
#
#
# class CartInfo(BaseModel):
#
#     class Meta:
#         verbose_name = '购物车商品信息'
#         verbose_name_plural = verbose_name

apps/cart/views.py
from django.shortcuts import render
from django.views.generic import View
from django.http import JsonResponse
from goods.models import GoodsSKU
from django_redis import get_redis_connection
from utils.mixin import LoginRequiredMixin


# Create your views here.


# /cart/add
class CartAddView(View):
    """购物车记录添加"""

    # 添加到购物车：
    # 1:请求方式：采用ajax post
    # 如果涉及到数据的修改（新增、更新、修改），采用post
    # 如果只涉及到数据的获取，采用get
    # 2:传递参数：商品ID(sku_id)数量(count)
    # ajax发起的请求都在后台，在浏览器上看不到效果
    def post(self, request):
        """购物车记录的添加"""
        user = request.user
        if not user.is_authenticated:
            # 用户未登录
            return JsonResponse({'res': 0, 'errmsg': '请先登录'})

        # 接收数据
        sku_id = request.POST.get('sku_id')
        count = request.POST.get('count')
        # 数据校验
        if not all([sku_id, count]):
            return JsonResponse({'res': 1, 'errmsg': '数据不完整'})
        # 校验添加的商品数量
        try:
            count = int(count)
        except Exception as e:
            return JsonResponse({'res': 2, 'errmsg': '商品数目出错'})

        # 校验商品是否存在
        try:
            sku = GoodsSKU.objects.get(id=sku_id)
        except GoodsSKU.DoesNotExist:
            # 商品不存在
            return JsonResponse({'res': 3, 'errmsg': '商品不存在'})

        # 业务处理：添加购物车记录
        # 先尝试获取sku_id的值:hget cart_key 属性
        conn = get_redis_connection('default')
        cart_key = 'cart_{}'.format(user.id)
        cart_count = conn.hget(cart_key, sku_id)  # 如果sku_id在hash中不存在，hget返回的是None
        if cart_count:
            # 累加购物车中商品的数目
            count += int(cart_count)

        # 校验商品中的库存
        if count > sku.stock:
            return JsonResponse({'res': 4, 'errmsg': '商品库存不足'})

        # 设置hash中sku_id对应的值
        conn.hset(cart_key, sku_id, count)  # 如果存在，就增加.如果不存在，就添加

        # 计算用户购物车中商品的条目数
        total_count = conn.hlen(cart_key)
        # 返回应答
        return JsonResponse({'res': 5, 'total_count': total_count, 'message': '添加成功'})


# /cart/
class CartInfoView(LoginRequiredMixin, View):
    """购物车页面显示"""

    def get(self, request):
        """显示"""
        # 获取登录的用户
        user = request.user

        # 获取用户购物车中商品的信息
        conn = get_redis_connection('default')
        cart_key = 'cart_{}'.format(user.id)

        # 获取{'商品ID':商品数目}
        cart_dict = conn.hgetall(cart_key)

        skus = list()

        # 保存用户购物车中商品的总数目和总价格
        total_count = 0
        total_price = 0

        for sku_id, count in cart_dict.items():  # items() 函数以列表返回可遍历的(键, 值) 元组数组。

            # 根据商品的ID获取商品的信息
            sku = GoodsSKU.objects.get(id=sku_id)

            # 计算商品的小计
            amount = sku.price * int(count)  # 数量遍历出来的是字符串，需要转换成int形式

            # 动态给sku对象增加属性amount,保存商品的小计
            sku.amount = amount

            # 动态给sku对象增加属性count,保存购物车中对应商品的数量
            sku.count = int(count)

            # 添加
            skus.append(sku)

            # 累加计算商品的总数目和总价格
            total_count += int(count)
            total_price += amount

        # 遍历获取商品的信息
        # 组织上下文
        context = {
            'total_count': total_count,
            'total_price': total_price,
            'skus': skus,
        }
        # 使用模板
        return render(request, template_name='cart.html', context=context)


# 更新购物车记录
# 采用ajax POST请求
# 前端需要传递的参数包括商品id(sku_id)，更新的商品数量(count)
# /cart/update
class CartUpdateView(View):
    """购物车记录更新"""

    def post(self, request):
        """购物车记录更新"""
        # 接受数据
        user = request.user
        if not user.is_authenticated:
            # 用户未登录
            return JsonResponse({'res': 0, 'errmsg': '请先登录'})
        # 接收数据
        sku_id = request.POST.get('sku_id')
        count = request.POST.get('count')
        # 数据校验
        if not all([sku_id, count]):
            return JsonResponse({'res': 1, 'errmsg': '数据不完整'})
        # 校验添加的商品数量
        try:
            count = int(count)
        except Exception as e:
            return JsonResponse({'res': 2, 'errmsg': '商品数目出错'})

        # 校验商品是否存在
        try:
            sku = GoodsSKU.objects.get(id=sku_id)
        except GoodsSKU.DoesNotExist:
            # 商品不存在
            return JsonResponse({'res': 3, 'errmsg': '商品不存在'})

        # 业务处理：更新购物车记录
        conn = get_redis_connection('default')
        cart_key = 'cart_{}'.format(user.id)

        # 校验商品的库存
        if count > sku.stock:
            return JsonResponse({'res': 4, 'errmsg': '商品库存不足'})

        # 更新
        conn.hset(cart_key, sku_id, count)

        # 计算用户购物车中商品的总件数{'1':5,'2':3,}
        vals = conn.hvals(cart_key)

        total_count = 0
        for val in vals:
            total_count += int(val)

        # 返回应答
        return JsonResponse({'res': 5,
                             'total_count': total_count,
                             'message': '更新成功', })


# 删除购物车记录
# 采用ajax POST 请求
# 前端需要传递的参数：商品ID(sku_Id)
class CartDeleteView(View):
    """购物车记录的删除"""

    def post(self, request):
        """购物车记录删除"""
        user = request.user
        if not user.is_authenticated:
            return JsonResponse({'res': 0,
                                 'errmsg': '请先登录'})
        # 接收参数
        sku_id = request.POST.get('sku_id')

        # 数据校验
        if not sku_id:
            return JsonResponse({'res': 1,
                                 'errmsg': '无效的商品ID'})
        # 校验商品是否存在
        try:
            sku = GoodsSKU.objects.get(id=sku_id)
        except GoodsSKU.DoesNotExist:
            # 商品不存在
            return JsonResponse({'res': 2,
                                 'errmsg': '商品不存在'})
        # 业务处理：删除购物车记录
        conn = get_redis_connection('default')
        cart_key = 'cart_{}'.format(user.id)
        # 删除 hdel
        conn.hdel(cart_key, sku_id)
        # 计算用户购物车中商品的总件数{'1':5,'2':3}
        total_count = 0
        vals = conn.hvals(cart_key)
        for val in vals:
            total_count += int(val)

        # 返回应答
        return JsonResponse({'res': 3,
                             'total_count': total_count,
                             'message': '删除成功'})

templates/base.html
{# 首页  注册 登录 #}
{% load staticfiles %}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">

<head>
    <meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
    {# 网页标题内容块 #}
    <title>{% block title %} {% endblock title %}</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
    {# 网页顶部引入文件块 #}
    {% block top_files %}{% endblock top_files %}
</head>

<body>

{# 网页顶部欢迎信息块 #}
{% block  head_con %}
    <div class="header_con">
        <div class="header">
            <div class="welcome fl">欢迎来到天天生鲜!</div>
            <div class="fr">
                {% if user.is_authenticated %}
                    <div class="login_btn fl">
                        欢迎您：<em>{{ user.username }}</em>
                        <span>|</span>
                        <a href="{% url 'user:logout' %}">退出</a>
                    </div>
                {% else %}
                    <div class="login_btn fl">
                        <a href="{% url 'user:login' %}">登录</a>
                        <span>|</span>
                        <a href="{% url 'user:register' %}">注册</a>
                    </div>
                {% endif %}
                <div class="user_link fl">
                    <span>|</span>
                    <a href="{% url 'user:user' %}">用户中心</a>
                    <span>|</span>
                    <a href="{% url 'cart:show' %}">我的购物车</a>
                    <span>|</span>
                    <a href="{% url 'user:order' %}">我的订单</a>
                </div>
            </div>
        </div>
    </div>
{% endblock head_con %}

{# 网页顶部搜索框 #}
{% block search_bar %}
    <div class="search_bar clearfix">
        <a href="index.html" class="logo fl"><img src="{% static 'images/logo.png' %}"></a>
        <div class="search_con fl">
            <form method="get" action="/search">
                <input type="text" class="input_text fl" name="q" placeholder="搜索商品">
                <input type="submit" class="input_btn fr" name="" value="搜索">
            </form>

        </div>
        <div class="guest_cart fr">
            <a href="#" class="cart_name fl">我的购物车</a>
            <div class="goods_count fl" id="show_count">{{ cart_count }}</div>
        </div>
    </div>
{% endblock search_bar %}

{# 网页主体内容块 #}
{% block body %}
{% endblock body %}


<div class="footer">
    <div class="foot_link">
        <a href="#">关于我们</a>
        <span>|</span>
        <a href="#">联系我们</a>
        <span>|</span>
        <a href="#">招聘人才</a>
        <span>|</span>
        <a href="#">友情链接</a>
    </div>
    <p>CopyRight © 2019 北京天天生鲜信息技术有限公司 All Rights Reserved</p>
    <p>电话：010-****888 京ICP备*******8号</p>
</div>

{# 网页底部html元素块 #}
{% block bottom %}
{% endblock bottom %}

{# 网页底部引入文件块 #}
{% block bottomfiles %}
{% endblock bottomfiles %}

</body>
</html>

templates/base_detail_list.html
{# 详情页 列表页 #}
{% extends 'base.html' %}
{% load staticfiles %}
{# 网页主体内容块 #}
{% block body %}
    <div class="navbar_con">
        <div class="navbar clearfix">
            <div class="subnav_con fl">
                <h1>全部商品分类</h1>
                <span></span>
                <ul class="subnav">
                    {% for type in types %}
                    <li><a href="{% url 'goods:list' type.id 1 %}" class="{{ type.logo }}">{{ type.name }}</a></li>
                    {% endfor %}
                </ul>
            </div>
            <ul class="navlist fl">
                <li><a href="">首页</a></li>
                <li class="interval">|</li>
                <li><a href="">手机生鲜</a></li>
                <li class="interval">|</li>
                <li><a href="">抽奖</a></li>
            </ul>
        </div>
    </div>
    {# 详情页、列表页主体内容块 #}
    {% block main_content %}

    {% endblock main_content %}
{% endblock body %}

templates/base_user_center.html
{# 用户中心3页面 #}

{% extends 'base_no_cart.html' %}
{% load staticfiles %}

{% block title %}
    天天生鲜-用户中心
{% endblock title %}

{% block page_title %}
    用户中心
{% endblock page_title %}

{% block body %}
    <div class="main_con clearfix">
        <div class="left_menu_con clearfix">
            <h3>用户中心</h3>
            <ul>
                {# url反向解析格式：namespace：name #}
                <li><a href="{% url 'user:user' %}"{% if page == 'user' %} class="active"{% endif %}>· 个人信息</a></li>
                <li><a href="{% url 'user:order' %}"{% if page == 'order' %} class="active"{% endif %}>· 全部订单</a></li>
                <li><a href="{% url 'user:address' %}"{% if page == 'address' %} class="active"{% endif %}>· 收货地址</a>
                </li>
            </ul>
        </div>
        {# 用户中心右侧内容块 #}
        {% block right_content %}

        {% endblock right_content %}
    </div>
{% endblock body %}

templates/detail.html
{% extends 'base_detail_list.html' %}
{% load staticfiles %}

{% block title %}
    天天生鲜-商品详情
{% endblock title %}

{% block main_content %}
    {% csrf_token %}



    <div class="breadcrumb">
        <a href="#">全部分类</a>
        <span>></span>
        <a href="#">{{ sku.type }}</a>
        <span>></span>
        <a href="#">商品详情</a>
    </div>

    <div class="goods_detail_con clearfix">
        <div class="goods_detail_pic fl"><img src="{{ sku.image.url }}"></div>

        <div class="goods_detail_list fr">
            <h3>{{ sku.name }}</h3>
            <p>{{ sku.desc }}</p>
            <div class="prize_bar">

                <span class="show_pirze">¥<em>{{ sku.price }}</em></span>
                <span class="show_unit">单  位：{{ sku.unite }}</span>
            </div>
            <div class="goods_num clearfix">

                <div class="num_name fl">数 量：</div>
                <div class="num_add fl">
                    <input type="text" class="num_show fl" value="1">
                    <a href="javascript:;" class="add fr">+</a>
                    <a href="javascript:;" class="minus fr">-</a>
                </div>
            </div>

            <div class="total">总价：<em>16.800000元</em></div>
            <div class="operate_btn">

                <a href="javascript:;" class="buy_btn">立即购买</a>
                <a href="javascript:;" sku_id="{{ sku.id }}" class="add_cart" id="add_cart">加入购物车</a>
            </div>
        </div>
    </div>

    <div class="main_wrap clearfix">
        <div class="l_wrap fl clearfix">
            <div class="new_goods">
                <h3>新品推荐</h3>
                <ul>
                    {% for sku in new_skus %}


                        <li>
                            <a href="{% url 'goods:detail' sku.id %}"><img src="{{ sku.image.url }}"></a>
                            <h4><a href="{% url 'goods:detail' sku.id %}">{{ sku.name }}</a></h4>
                            <div class="prize">￥{{ sku.price }}</div>
                        </li>

                    {% endfor %}


                </ul>
            </div>
        </div>

        <div class="r_wrap fr clearfix">
            <ul class="detail_tab clearfix">
                <li class="active">商品介绍</li>
                <li>评论</li>
            </ul>

            <div class="tab_content">
                <dl>
                    <dt>商品详情：</dt>
                    <dd>
                        {#关闭转义#}
                        {{ sku.goods.detail |safe }}
                    </dd>
                </dl>
            </div>

            <div class="tab_content">
                <dl>
                    {% for order in sku_orders %}
                        <dt>评论时间：{{ order.update_time }}&nbsp;&nbsp;用户名：{{ order.order.user.username }}</dt>
                        <dd>
                            评论内容{{ order.comment }}
                        </dd>
                    {% endfor %}


                </dl>
            </div>

        </div>
    </div>
{% endblock main_content %}

{% block bottom %}
    <div class="add_jump"></div>
{% endblock bottom %}


{% block bottomfiles %}
    <script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
    <script type="text/javascript">
        update_goods_amount();

        //计算商品总价
        function update_goods_amount() {

            //获取商品的单价和数量
            price = $('.show_pirze').children('em').text();
            count = $('.num_show').val();
            //计算商品的总价
            price = parseFloat(price);
            count = parseInt(count);
            //计算总价
            amount = price * count;
            //设置商品的总价
            $('.total').children('em').text(amount.toFixed(2) + '元');
        }

        //增加商品的数量
        $('.add').click(
            function () {
                //获取商品原有的数目
                count = $('.num_show').val();
                //加1
                count = parseInt(count) + 1;
                //重新设置商品的数目
                $('.num_show').val(count);
                //更新商品的总价
                update_goods_amount();

            }
        )


        //减少商品的数量
        $('.minus').click(
            function () {
                //获取商品原有的数目
                count = $('.num_show').val();
                //减少1
                count = parseInt(count) - 1;
                if (count < 1) {
                    count = 1;
                }
                //重新设置商品的数目
                $('.num_show').val(count);
                //更新商品的总价
                update_goods_amount();

            }
        )

        //手动输入商品的数量
        $('.num_show').blur(function () {
            //获取用户输入的数目
            count = $(this).val();
            //校验 count是否合法
            if (isNaN(count) || count.trim().length == 0 || parseInt(count) < 1) {
                //重新设置商品的数目
                count = 1;
            }
            $(this).val(parseInt(count));
            //更新商品的总价
            update_goods_amount();

        })

        //获取adda_cart div元素左上角的坐标
        var $add_x = $('#add_cart').offset().top;
        var $add_y = $('#add_cart').offset().left;

        //获取show_count div元素左上角的坐标
        var $to_x = $('#show_count').offset().top;
        var $to_y = $('#show_count').offset().left;


        $('#add_cart').click(function () {


            //获取商品的ID和数量
            sku_id = $(this).attr('sku_id');
            count = $('.num_show').val();
            csrf = $('input[name="csrfmiddlewaretoken"]').val();


            //alert(sku_id+':'+count);

            //组织参数
            params = {
                'sku_id': sku_id,
                'count': count,
                'csrfmiddlewaretoken': csrf,

            }
            //发起ajax post请求，访问/cart/add,传递参数:sku_id,count
            $.post('/cart/add', params, function (data) {
                if (data.res == 5) {
                    //添加成功
                    $(".add_jump").css({'left': $add_y + 80, 'top': $add_x + 10, 'display': 'block'})
                    $(".add_jump").stop().animate({
                            'left': $to_y + 7,
                            'top': $to_x + 7
                        },
                        "fast", function () {
                            $(".add_jump").fadeOut('fast', function () {
                                //重新设置用户购物车中商品的条目数
                                $('#show_count').html(data.total_count);
                            });
                        });
                } else {
                    //添加失败
                    alert(data.errmsg);
                }

            })

        })
    </script>

{% endblock bottomfiles %}

templates/index.html
{% extends 'base.html' %}

{% load staticfiles %}

{% block title %} 天天生鲜-首页 {% endblock title %}

{% block top_files %}

    <script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/jquery-ui.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/slide.js' %}"></script>

{% endblock top_files %}

{% block body %}

    <div class="navbar_con">
        <div class="navbar">
            <h1 class="fl">全部商品分类</h1>
            <ul class="navlist fl">
                <li><a href="">首页</a></li>
                <li class="interval">|</li>
                <li><a href="">手机生鲜</a></li>
                <li class="interval">|</li>
                <li><a href="">抽奖</a></li>
            </ul>
        </div>
    </div>

    <div class="center_con clearfix">
        <ul class="subnav fl">

            {% for type in types %}

                <li><a href="#model0{{ forloop.counter }}" class="{{ type.logo }}">{{ type.name }}</a></li>

            {% endfor %}

        </ul>
        <div class="slide fl">
            <ul class="slide_pics">

                {% for banner in goods_banners %}

                    <li>
                        <a href="{% url 'goods:detail' banner.sku.id %}">
                            <img src="{{ banner.image.url  }}" alt="幻灯片">
                        </a>
                    </li>

                {% endfor %}


            </ul>
            <div class="prev"></div>
            <div class="next"></div>
            <ul class="points"></ul>
        </div>
        <div class="adv fl">
            {% for banner in promotion_banners %}

                <a href="{{ banner.url }}">
                    <img src="{{ banner.image.url }}">
                </a>

            {% endfor %}


        </div>
    </div>

    {% for type in types %}
        <div class="list_model">
            <div class="list_title clearfix">
                <h3 class="fl" id="model{{ forloop.counter }}">{{ type.name }}</h3>
                <div class="subtitle fl">
                    <span>|</span>
                    {% for banner in type.title_banners %}
                        <a href="{% url 'goods:detail' banner.sku.id %}">{{ banner.sku.name }}</a>
                    {% endfor %}
                </div>
                <a href="#" class="goods_more fr" id="fruit_more">查看更多 ></a>
            </div>

            <div class="goods_con clearfix">
                <div class="goods_banner fl"><img src="{{ type.image.url }}"></div>
                <ul class="goods_list fl">

                    {% for banner in type.image_banners %}
                        <li>
                            <h4><a href="{% url 'goods:detail' banner.sku.id %}">{{ banner.sku.name }}</a></h4>
                            <a href="{% url 'goods:detail' banner.sku.id %}"><img src="{{ banner.sku.image.url }}"></a>
                            <div class="prize">¥ {{ banner.sku.price }}</div>
                        </li>
                    {% endfor %}

                </ul>
            </div>
        </div>
    {% endfor %}




{% endblock body %}

templates/list.html
{% extends 'base_detail_list.html' %}
{% block title %}
    天天生鲜-商品列表
{% endblock title %}

{% block main_content %}



    <div class="breadcrumb">
        <a href="#">全部分类</a>
        <span>></span>
        <a href="#">{{ type.name }}</a>
    </div>

    <div class="main_wrap clearfix">
        <div class="l_wrap fl clearfix">
            <div class="new_goods">
                <h3>新品推荐</h3>
                <ul>
                    {% for sku in  new_skus %}
                        <li>
                            <a href="{% url 'goods:detail' sku.id %}"><img src="{{ sku.image.url }}"></a>
                            <h4><a href="{% url 'goods:detail' sku.id %}">{{ sku.name }}</a></h4>
                            <div class="prize">￥{{ sku.price }}</div>
                        </li>
                    {% endfor %}

                </ul>
            </div>
        </div>

        <div class="r_wrap fr clearfix">
            <div class="sort_bar">
                <a href="{% url 'goods:list' type.id 1 %}"{% if sort ==  'default' %} class="active"{% endif %}>默认</a>
                <a href="{% url 'goods:list' type.id 1 %}?sort=price"
                   {% if sort ==  'price' %}class="active"{% endif %}>价格</a>
                <a href="{% url 'goods:list' type.id 1 %}?sort=hot"
                   {% if sort ==  'hot' %}class="active"{% endif %}>人气</a>
            </div>

            <ul class="goods_type_list clearfix">
                {% for sku in skus_page.object_list %}
                    <li>
                        <a href="{% url 'goods:detail' sku.id %}"><img src="{{ sku.image.url }}"></a>
                        <h4><a href="{% url 'goods:detail' sku.id %}">{{ sku.name }}</a></h4>
                        <div class="operate">
                            <span class="prize">￥{{ sku.price }}</span>
                            <span class="unit">{{ sku.price }}/{{ sku.unite }}</span>
                            <a href="#" class="add_goods" title="加入购物车"></a>
                        </div>
                    </li>
                {% endfor %}


            </ul>

            <div class="pagenation">
                {% if skus_page.has_previous %}
                    <a href="{% url 'goods:list' type.id  skus_page.previous_page_number %}?sort={{ sort }}">
                        <上一页
                    </a>
                {% endif %}

                {% for pindex in skus_page.paginator.page_range %}
                    {% if pindex == skus_page.number %}
                        <a href="{% url 'goods:list' type.id pindex %}?sort={{ sort }}" class="active">{{ pindex }}</a>
                    {% else %}
                        <a href="{% url 'goods:list' type.id  pindex %}?sort={{ sort }}">{{ pindex }}</a>
                    {% endif %}
                {% endfor %}



                {% if skus_page.has_next %}
                    <a href="{% url 'goods:list' type.id  skus_page.next_page_number %}?sort={{ sort }}">下一页></a>
                {% endif %}

            </div>
        </div>
    </div>
{% endblock main_content %}